import { mkdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { chromium } from "playwright";

/**
 * Captures the demo screenshots committed to `docs/screenshots/`. Run
 * against a live demo stack (`docker compose ... up`, migrated and seeded
 * with `pnpm seed:demo`) at BASE_URL (default http://localhost:8080/).
 *
 * Screenshots use the built-in demo dataset (synthetic data generated by
 * `pnpm seed:demo`) — no real financial data is shown.
 */

const BASE_URL = process.env.SCREENSHOT_BASE_URL ?? "http://localhost:8080/";
const OUT_DIR = fileURLToPath(new URL("../../../docs/screenshots/", import.meta.url));

interface Shot {
  file: string;
  path: string;
  waitForText: string;
}

const SHOTS: Shot[] = [
  { file: "dashboard.png", path: "", waitForText: "Painel" },
  { file: "investments.png", path: "investimentos", waitForText: "Investimentos" },
  { file: "purchases.png", path: "compras", waitForText: "Compras" },
];

async function main(): Promise<void> {
  await mkdir(OUT_DIR, { recursive: true });

  const browser = await chromium.launch();
  const context = await browser.newContext({
    viewport: { width: 1280, height: 900 },
    colorScheme: "dark",
  });
  const page = await context.newPage();

  for (const shot of SHOTS) {
    const url = new URL(shot.path, BASE_URL).toString();
    await page.goto(url, { waitUntil: "networkidle" });
    await page.getByText(shot.waitForText, { exact: false }).first().waitFor({ timeout: 15000 });
    await page.waitForTimeout(500);
    await page.screenshot({ path: path.join(OUT_DIR, shot.file) });
    console.log(`captured ${shot.file}`);
  }

  await browser.close();
}

await main();
